sources:
  - name: LogicaHealth Sandbox v3
    handler:
        fhir:
          endpoint: https://api.logicahealth.org/PatientCloud10STU3/open

serve:
  port: 4000
  exampleQuery: ./example-query.graphql